from datetime import datetime

seed_segments = [
  {
    "id": "seg_001",
    "name": "A10 Segment 12",
    "geometry": {
      "point": { "lat": 52.2053, "lng": 0.1218 },
      "line": { "type": "LineString", "coordinates": [[0.1201, 52.2060], [0.1235, 52.2042]] },
    },
    "emissionFactors": { "co2e": 145.2, "unit": "gCO2e/km" },
    "roadType": "primary",
    "speedLimit": 50,
    "lastUpdated": datetime.now().isoformat(),
    "source": "backend-calculation",
  },
  {
    "id": "seg_002",
    "name": "M11 Junction 8",
    "geometry": {
      "point": { "lat": 51.985, "lng": 0.1565 },
      "line": { "type": "LineString", "coordinates": [[0.1540, 51.987], [0.1590, 51.983]] },
    },
    "emissionFactors": { "co2e": 210.8, "unit": "gCO2e/km" },
    "roadType": "motorway",
    "speedLimit": 70,
    "lastUpdated": datetime.now().isoformat(),
    "source": "backend-calculation",
  },
  {
    "id": "seg_003",
    "name": "B1046 Rural Section",
    "geometry": {
      "point": { "lat": 52.155, "lng": -0.025 },
      "line": { "type": "LineString", "coordinates": [[-0.030, 52.157], [-0.020, 52.153]] },
    },
    "emissionFactors": { "co2e": 72.5, "unit": "gCO2e/km" },
    "roadType": "secondary",
    "speedLimit": 40,
    "lastUpdated": datetime.now().isoformat(),
    "source": "backend-calculation",
  },
  {
    "id": "seg_004",
    "name": "A14 Interchange",
    "geometry": {
      "point": { "lat": 52.235, "lng": 0.155 },
      "line": { "type": "LineString", "coordinates": [[0.150, 52.237], [0.160, 52.233]] },
    },
    "emissionFactors": { "co2e": 188.3, "unit": "gCO2e/km" },
    "roadType": "primary",
    "speedLimit": 60,
    "lastUpdated": datetime.now().isoformat(),
    "source": "backend-calculation",
  },
  {
    "id": "seg_005",
    "name": "Station Road Urban",
    "geometry": { "point": { "lat": 52.195, "lng": 0.135 } },
    "emissionFactors": { "co2e": 95.0, "unit": "gCO2e/km" },
    "roadType": "residential",
    "speedLimit": 30,
    "lastUpdated": datetime.now().isoformat(),
    "source": "backend-calculation",
  },
  {
    "id": "seg_006",
    "name": "A1303 Newmarket Rd",
    "geometry": {
      "point": { "lat": 52.202, "lng": 0.148 },
      "line": { "type": "LineString", "coordinates": [[0.140, 52.204], [0.156, 52.200]] },
    },
    "emissionFactors": { "co2e": 162.7, "unit": "gCO2e/km" },
    "roadType": "primary",
    "speedLimit": 40,
    "lastUpdated": datetime.now().isoformat(),
    "source": "backend-calculation",
  },
  {
    "id": "seg_007",
    "name": "M11 Southbound S3",
    "geometry": {
      "point": { "lat": 52.05, "lng": 0.13 },
      "line": { "type": "LineString", "coordinates": [[0.128, 52.055], [0.132, 52.045]] },
    },
    "emissionFactors": { "co2e": 255.1, "unit": "gCO2e/km" },
    "roadType": "motorway",
    "speedLimit": 70,
    "lastUpdated": datetime.now().isoformat(),
    "source": "backend-calculation",
  },
  {
    "id": "seg_008",
    "name": "Hills Road Cycle Corridor",
    "geometry": { "point": { "lat": 52.19, "lng": 0.125 } },
    "emissionFactors": { "co2e": 45.3, "unit": "gCO2e/km" },
    "roadType": "residential",
    "speedLimit": 20,
    "lastUpdated": datetime.now().isoformat(),
    "source": "backend-calculation",
  },
]
